### ISSUE TITLE
Option to extract games to a platform folder

### ISSUE THREAD

**Issue by fraganator** [fraganator/archive-cache-manager#22]
[Forum submission](https://forums.launchbox-app.com/topic/35010-archive-cache-manager/?do=findComment&comment=407572):

"Can we extract roms to a path based on platform? For instance, since Dolphin will load NGC and Wii games, I would like to be able to extract them to their respective platform folder in order to give them specific configurations within Retroarch, like setting shaders and core options based on Content Folder.

Something like ".\ArchiveCache\Nintendo GameCube\GAME.iso" would be helpful I think.

Using Launchbox's default 7z settings, all platform games are extracted to a ".\ThirdParty\7z\Temp" folder and I can't target Content Folder based settings in Retroarch that way as all roms belong to the same Temp folder."

**Comment by fraganator** [comment]
Immediate thought is to extract to cache as normal, then have a post extraction step to create a platform folder, and create symlinks in the platform folder to the cached files. Would need to update paths returned to LaunchBox to be the symlinks. Also check RetroArch can handle symlinks.

**Comment by nixxou** [comment]
I was checking on the Dev branch, it's looking great.
![image](https://user-images.githubusercontent.com/45721836/163481643-c6bd83f8-1f17-457f-bd1c-ec9aa4f0e74e.png)
Still, i have a small suggestion, is there a way to use custom instead of default/title/emulator ... ?
It's related to https://github.com/fraganator/archive-cache-manager/issues/4 and i would prefer to keep path as short as possible (n64, gb,psx instead of Nintendo 64, Game Boy and Playstation for exemple) to avoid the issue with path over 255 chars.

**Comment by fraganator** [comment]
Thanks for the feedback :+1:
I'll look at adding a custom launch path option. Unfortunately it won't help with the path too long issue, as the archive will still be extracted to the `filename + hash` path first.

Version 2.12 of the plugin is feature complete, but needs a little polish before release. Once it's released, I'll revisit #4 and maybe add some options to handle what to do when the path is too long.

**Comment by fraganator** [comment]
This is now available in v2.12. The custom launch path idea is being tracked in #26.
