### ISSUE TITLE
Feature: Add "M3U Name" option that preserves disc # to work with The Bezel Project

### ISSUE THREAD

**Issue by mtyrealhanla** [fraganator/archive-cache-manager#36]
When using [The Bezel Project](https://github.com/thebezelproject/BezelProject), there are override config files per game in the core folder in RetroArch. When extracting a multi-disc game and creating an m3u file, the m3u filename needs to match the rom name in order for RetroArch to pickup the override, otherwise it falls back to a system default bezel. 

It seems that maybe just a new "M3U Name" option to preserve the ROM name entirely for the m3u file will do that trick as I tested  that out myself locally. The Bezel project generally just has a config file for each disc (so there is always 1 per rom) that point to the same bezel image.

Curious on your thoughts. I actually forked this a ways back to implement some of the stuff you did for 2.12 to make multi disc games work better but I have completely abandoned that for the latest version. It is perfection. Really appreciate it.

![image](https://user-images.githubusercontent.com/10082024/214734326-b8baa3a0-a627-4c83-b23d-6bd50b9837e5.png)

**Comment by mtyrealhanla** [comment]
And I may see if I can get in there and submit a PR if you think its a good idea and you don't have the bandwidth. (Otherwise may just re-fork!)

**Comment by fraganator** [comment]
I haven't used the bezel project. so thanks for bringing up this issue. I agree an additional option for M3U name should cover it, something simple like "ROM name".

There's a couple of other updates I was planning on adding to the plugin over the weekend, so will implement this too. That said if you don't see any progress on the issue, feel free to fork and submit a PR :)

**Comment by mtyrealhanla** [comment]
Much appreciated, yes I will keep a look out. Thanks for the one and only 100% must have LB plugin

**Comment by fraganator** [comment]
Hi @mtyrealhanla , I've added in the new M3U Name option called _ROM Filename_ which will use the filename of the launched ROM / additional app. So if disc 1 of the game is launched, the m3u name will be _Resident Evil 2 (USA) (Disc 1).m3u_, and if disc 2 is launched it will be _Resident Evil 2 (USA) (Disc 2).m3u_.

Thinking about the change a little more, there are some RetroArch cores that use the filename to determine which memory card to use. So there might be a situation where the save progress is on the memory card for disc 1, and then disc 2 is later launched (with a different m3u name). Disc 2 will have its own separate memory card and the progress from disc 1 will be unavailable.

I'm thinking rather than use the launched ROM filename (which could be any disc), the m3u filename is always based on the first disc. So launching _Resident Evil 2 (USA) (Disc **2**).cue_ will result in _Resident Evil 2 (USA) (Disc **1**).m3u_. This should satisfy both the memory card requirements and the bezel project requirements. Any thoughts?

Also thanks for the positive feedback on the plugin, it's really appreciated.

**Comment by mtyrealhanla** [comment]
Oh interesting. Nice catch. Ya I believe that would cover all the bases.
Depending on complexity you could leave both the options (Rom name, Rom
name + first disc) just in case, but then becomes a fun naming situation
😜.

**Comment by fraganator** [comment]
Thanks for the input, apologies for not replying sooner. I think I'll just have an option for the disc 1 filename for now, and expand it later if required. All going well the next release should be available in within 24h.

**Comment by fraganator** [comment]
Added to release [v2.16](https://github.com/fraganator/archive-cache-manager/releases/tag/v2.16).
